---
- name: Change root password
  hosts: "{{ hosts_to_update }}"
  become: yes

  vars:
    root_password: "{{ replacement_root_password }}"
    root_password_salt: afEMnZBOGgynhoqA

  tasks:
    - name: Change root password
      user:
        name: root
        password: "{{ root_password | password_hash(salt=root_password_salt) }}"
