---
- name: configure the firewall
  vars:
    hosts_to_configure: all
  hosts: "{{ hosts_to_configure }}" 

  tasks:

    - name: Bring down repo with git
      git:
        repo: https://github.com/jimbarlow/ansible-demo
        dest: downloaded
      delegate_to: localhost

    - name: 
      include_role: 
        name: 'downloaded/ipainstall/roles/ipafirewall'
      become: true

    - name:
      include_role:
        name: 'downloaded/ipainstall/roles/ipafwconfig'
      become: true
   
