---
- name: configure the firewall
  vars:
    ports:
        - 22/tcp
        - 80/tcp
        - 443/tcp
        - 53/tcp
        - 9000/tcp
        - 6443/tcp
        - 22623/tcp
        - 2049/tcp
        - 2049/udp
  hosts: all 

  tasks:
    - name: install firewalld
      yum: 
        name: firewalld
        state: latest
          
    - name: start and enable firewalld service
      service:
        name: firewalld
        state: started
        enabled: true
      tags: startfirewalld

    - name: firewall services config
      firewalld:
        state: enabled
        immediate: True
        permanent: True
        port: "{{ item }}"
      with_items: "{{ ports }}"
    
    - name: restart firewalld
      service:
        name: firewalld
        state: started
