---
- name: Set things up for the extra drive
  hosts: all 
  become: true
  remote_user: devops
  vars:
    howbig: 10g
  tasks: 
  - name: Geate a logical volume group on /dev/vdb
    lvg:
      vg: vg.supplemental
      pvs: /dev/vdb
      state: present

  - name: Create a Logical Volume in the vg
    lvol:
      vg: vg.supplemental
      lv: jimstest
#      size: 19g
#      size: +100%FREE
      size: "{{ howbig }}"

  - name: Create a fileystem on the Logical Volume
    filesystem:
      fstype: ext4
      dev: /dev/mapper/vg.supplemental-jimstest
    register: result


#   - name: Let's make the mount point in fstab
#     lineinfile: 
#       path: /etc/fstab
#       line: /dev/mapper/vg.supplemental-jimstest  /mnt   ext4 defaults 0 0
#       insertafter: '^//dev//mapper//rhel-swap*'
#     
#   - name: Mount the new fileysystem on mount
#     command: 'mount -t ext4 /dev/mapper/vg.supplemental-jimstest'

  - name: Setup the /etc/fstab
    mount:
      src: /dev/mapper/vg.supplemental-jimstest
      path: /mnt
      state: mounted
      fstype: ext4
      
...

