---
- name: Restore the snapshot we want
  vars:
    snapshot_name: ready2database
    which_hosts:
      - db1
      - db2
      - db3    
  hosts: "{{ virthost | default('jbarlow') }}"
  tasks:
    - name: Issue a Virsh snapshot revirt
      command: virsh snapshot-revert {{ item }} {{ snapshot_name }}
      become: True
      with_items: "{{ which_vms }}"     

# original script
#!/bin/bash
# sudo virsh snapshot-revert db1 ready2database
# sudo virsh snapshot-revert db2 ready2database
# sudo virsh snapshot-revert db3 ready2database
