---
- name: list the vms running on the host
  vars:
    vms_to_control:
      - db1
      - db2
      - db3
      - Server-A
      - Server-B
      - Server-C
    vmstate: running
  hosts: "{{ virthost | default('jbarlow') }}"
  # remote_user: root
  tasks:
    - name: "{{ vmstate }} VMs"
      virt:
          name: "{{ item }}"
          state: "{{ vmstate }}"
          # uri: 'lxc:///'  
      with_items: "{{ vms_to_control }}"

