---
- name: list the vms running on the host
  vars:
    vms_to_control:
      - db1
      - db2
      - db3
    vmstate: running
  hosts: "{{ virthost | default('localhost') }}"
  # remote_user: root
  tasks:
    - name: start vm
      virt:
          name: "{{ item }}"
          state: "{{ vmstate }}"
          # uri: 'lxc:///'  
      with_items: "{{ vms_to_control }}"

